PollingPolls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pollapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

pollapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'pollapp'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('polls/', views.PollListView.as_view(), name='poll_list'),
    path('<int:pk>/report/', views.ReportView.as_view(), name='poll_report'),
    path('polls/<int:pk>', views.PollDetailView.as_view(), name='poll_detail'),
    path('<int:question_id>', views.vote, name='vote'),
    path('taken_polls/', views.TakenListView.as_view(), name='taken_poll_list'),




]

accounts/models.py
from django.db import models

# Create your models here.

pollapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
now = timezone.now()


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    question_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class TakenPoll(models.Model):
    user = models.CharField(max_length=200)
    poll = models.CharField(max_length=200)
    poll_id = models.BigIntegerField()
    time_taken = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return "Poll ID:{} User:{}  Poll:{}".format(self.poll_id, self.user, self.poll)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username","first_name", "last_name", "password1", "password2")

    def save(self, commit=True):

        user = super(UserCreateForm, self).save(commit=False)

        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]


        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserCreateForm

class SignUpView(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

pollapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


from .models import Choice, Question, TakenPoll

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'index.html'

class PollListView(ListView):
    template_name = 'pollapp/poll_list.html'
    context_object_name = 'poll_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-question_date')[:10]

class PollDetailView(DetailView):
    model = Question
    template_name = 'pollapp/poll_detail.html'

class ReportView(DetailView):
    model = Question
    template_name = 'pollapp/poll_report.html'

@login_required
def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        # Redisplay the question voting form.
        return render(request, 'pollapp/poll_detail.html', {
        'question': question,
        'error_message': "You didn't select a choice.",
        })
    else:
        #check db is user has already taken the test
        question_taken_by_user = TakenPoll.objects.filter(user=request.user, poll=question, poll_id=question_id)

        #check if the db returns an empty list
        if len(question_taken_by_user) == 0:
             question_taken_by_user = False

        #if True Execute condition, False Skip condition and count vote
        if question_taken_by_user:
            return render(request, 'pollapp/poll_detail.html', {
            'question': question,
            'error_message': "You have Taken Poll Before, choose another",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()

            taken_poll = TakenPoll(user=request.user, poll=question, poll_id=question_id)
            taken_poll.save()

            return HttpResponseRedirect(reverse('pollapp:poll_report', args=(question.id,)))

class TakenListView(ListView):
    template_name = 'pollapp/taken_poll_list.html'
    context_object_name = 'taken_poll_list'

    def get_queryset(self):
        return TakenPoll.objects.filter(user=self.request.user)

pollapp/templates/poll_base.html
{%extends 'base.html'%}

{% block content%}
{% if user.is_authenticated%}
  <!-- Side navigation -->
  <div class="sidenav">
    <div class="top">
      <a href="{% url 'pollapp:taken_poll_list' %}">View Already Taking Polls</a>
    </div>
  </div>
{%endif%}

<!-- Page content -->
<div class="main">
  {% block poll_content%}

  {% endblock poll_content%}
</div>

{% endblock content%}

pollapp/templates/pollapp/poll_detail.html
{% extends 'poll_base.html' %}

{% block poll_content %}
  <div class="container top">
    <div class="alert alert-success">
      <h2>{{ question.question_text }}</h2>
    </div>

    {% if error_message %}
      <p style="width:500px;" class="alert alert-danger text-center">
        <strong><em>{{ error_message }}</em></strong>
      </p>
    {% endif %}

    <form action="{% url 'pollapp:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
      <div class="card-header">
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
      </div>
    {% endfor %}
    <input class="btn btn-lg btn-outline-success" type="submit" value="Vote" />
    </form>
  </div>
{% endblock poll_content%}

pollapp/templates/pollapp/poll_list.html
{% extends 'poll_base.html' %}

{% block poll_content %}
{% if user.is_authenticated %}
    <div class="container top">
      <div class="alert alert-info">
        <p>Available Poll Questions</p>
      </div>
      {% if poll_question_list %}
        <ul>
          {% for question in poll_question_list %}
            <li class="card-header"><a href="{% url 'pollapp:poll_detail' question.id%}">{{ question.question_text }}</a>
              <br><small>{{question.question_date}}</small>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No polls are available.</p>
      {% endif %}
    </div>
{%else%}
  <div class="container top">
    <div class="alert alert-info">
      <p>Available Poll Questions</p>
      <p><a href="{%url 'login'%}">Login</a> or <a href="{%url 'accounts:signup'%}">Create Account</a> to take Poll</p>
    </div>
    {% if poll_question_list %}
      <ul>
        {% for question in poll_question_list %}
          <li class="card-header">{{ question.question_text }}
            <br><small>{{question.question_date}}</small>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
{% endif %}
  </div>
{% endblock poll_content%}

pollapp/templates/pollapp/poll_report.html
{% extends 'poll_base.html' %}

{% block poll_content %}
  <div class="col-md-4 float-right container top">
    <div class="alert alert-info" role="alert">
      <h4 class="alert-heading">Thanks for voting!!</h4>
      <p>Aww yeah, you successfully voted on "{{ question.question_text }}"</p>
  <hr>
  <p class="mb-0">Whenever you want to, be sure to come back and vote on more polls</p>
</div>

  </div>

  <div class="col-md-8 float-left top">
    <h1>{{ question.question_text }}</h1>
    <ul>
      {% for choice in question.choice_set.all %}
        <li class="alert alert-success text-center">
          <h4>
            <span class="choice_text">{{ choice.choice_text|upper }}</span><br>
            <span class="choice_votes badge badge-light btn btn-lg">{{ choice.votes }}</span>
            <span class="choice_vote_text">vote{{ choice.votes|pluralize }}</span>
          </h4>
        </li>
      {% endfor %}
    </ul>
{% endblock poll_content%}

pollapp/templates/pollapp/taken_poll_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container top">
    <div class="alert alert-info">
      <p>You've Taken these polls</p>
    </div>
    {% if taken_poll_list %}
      <ul>
        {% for poll in taken_poll_list %}
          <li class="card-header"><a href="{% url 'pollapp:poll_report' poll.poll_id%}">{{ poll.poll }}</a>
            <br><small><em>You took this poll on {{poll.time_taken}}</em></small>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>You've not taken any poll yet. Click <a href="{%url 'pollapp:poll_list'%} "></a> to start.</p>
    {% endif %}
  </div>
{% endblock content%}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block page_name %}{%endblock%}PollingPolls</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap_resources/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pagecss.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'pollapp:home' %}"><em>PollingPolls</em></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger active">Hi, {{user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger btn btn-outline-warning" href="{%url 'logout'%}">Logout</a>
            </li>
            {%endif%}
            &nbsp;
            <li></li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger btn btn-primary active" href="{%url 'pollapp:home'%}">Home</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

            {% block content %}

            {% endblock content %}

    <!-- Footer -->
    <footer class="py-0 bg-dark fixed-bottom">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; <em>PollingPolls</em> 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap_resources/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap_resources/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

templates/index.html
{% extends 'base.html'%}
{% block content %}
<header class="bg-primary text-white">
  <div class="container text-center">
    <h1>Welcome to Polling Polls</h1>
    <p class="lead">Answer questions and help us with our research to make the world a better place.</p>
  </div>
</header>

{% if user.is_authenticated %}
&nbsp;
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="row">
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Polls Page</h5>
                  <p class="card-text">Welcome, <em><strong>{{user.first_name}} {{user.last_name}}</strong></em><br> Click to Start...</p>
                  <a href="{% url 'pollapp:poll_list'%}" class="btn btn-outline-success">Start</a>

                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">View Polls</h5>
                  <p class="card-text">View Polls you've taken before</p>
                  <a href="{% url 'pollapp:taken_poll_list' %}" class="btn btn-outline-primary">Polls</a>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>
{%else%}
&nbsp;
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="row">
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Create an Account or Login</h5>
                  <p class="card-text">To partake in the poll</p>
                  <a href="{% url 'login'%}" class="btn btn-outline-primary">Login</a>
                  <a href="{% url 'accounts:signup'%}" class="btn btn-outline-primary">Signup</a>

                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">View Polls</h5>
                  <p class="card-text">Click to View existing poll results</p>
                  <a href="{% url 'pollapp:poll_list' %}" class="btn btn-outline-primary">Polls</a>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
{% endblock content %}